name: 'Terraform Validator and Plan'

on:
  workflow_call:
    inputs:
      OIOI:
        required: true
        type: string

jobs:
  terraform-validator:
    name: Terraform Step Validator and Plan
    runs-on: poc-runner

    steps:
    - name: terraform validator
      run: |
        echo ${{inputs.OIOI}}
        echo validator
        whoami
        terraform version

    - name: terraform plan
      run: |
        echo plan