name: 'Terraform Validator and Plan'

on:
  workflow_call:
    inputs:
      TEST:
        required: true
        type: string

jobs:
  terraform-validator:
    name: poc-template
    runs-on: poc-runner

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: terraform validator
      run: |
        echo ${inputs.TEST}
        terraform validator

  terraform-plan:
    name: poc-template
    runs-on: poc-runner

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: terraform plan
      run: |
        terraform plan