name: 'Terraform Apply'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform-apply:
    name: Terraform Step Apply
    runs-on: poc-runner

    steps:
    - name: checkout code
      uses: actions/checkout@v3
    - run: echo "::set-env name=BRANCH_NAME::${{ github.head_ref }}"

    - name: Terraform Apply
      run: |
        terraform init -backend-config="./configs/backends/backend-${{ inputs.environment }}.tfvars"
        terraform apply -var="branch_name=$BRANCH_NAME" -auto-approve