name: 'Terraform Validate and Plan'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform-validate:
    name: Terraform Step Validate and Plan
    runs-on: poc-runner

    steps:

    - name: checkout code
      uses: actions/checkout@v3

    - name: terraform validate
      run: |
        terraform init -backend-config=/config/backends/backend-${{ inputs.environment }}.tfvars
        terraform validate

    - name: terraform plan
      run: |
        terraform plan