name: 'Terraform Apply'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform-apply:
    name: Terraform Step Apply
    runs-on: poc-runner

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Terraform Apply
      run: |
        terraform init -backend-config="./configs/backends/backend-${{ inputs.environment }}.tfvars"
        terraform apply -var="branch_name=${{ inputs.environment }}" -auto-approve