name: 'Terraform Validate and Plan'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform-validate:
    name: Terraform Step Validate and Plan
    runs-on: poc-runner

    steps:

    - name: checkout code
      uses: actions/checkout@v3

    - name: Set environment variables
      run: |
        export ${{ inputs.environment }}=$TERRAFORM-ENV
        if [ $TERRAFORM-ENV == "main" ]; then export $TERRAFORM-ENV=="prd"; fi
        echo $TERRAFORM-ENV
   
    - name: terraform validate
      run: |
        ls -lah
        echo ${{inputs.environment}}
        terraform init -backend-config="backend-$TERRAFORM-ENV.tfvars"
        terraform validate

    - name: terraform plan
      run: |
        terraform plan