name: 'Terraform Apply'

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform-apply:
    name: Terraform Step Apply
    runs-on: poc-runner

    steps:

    - name: check out code
      uses: actions/checkout@v3

    - name: Terraform Apply
      run: |
        terraform init -backend-config=/config/backends/backend-${{ inputs.environment }}.tfvars
        terraform apply -auto-approve